# https://wiki.archlinux.org/title/wayland#Detect_Xwayland_applications_visually
- name: install xeyes (to detect Xwayland applications)
  become: yes
  community.general.pacman:
    name: xorg-xeyes
    state: latest

- name: install gnome-tweaks
  become: yes
  community.general.pacman:
    name: gnome-tweaks
    state: latest

- name: install ddterm dependencies
  become: yes
  community.general.pacman:
    name:
      # https://github.com/ddterm/gnome-shell-extension-ddterm/blob/0c337ee220dfe270ae6674ea0d41194a1d9d878c/ddterm/app/dependencies.json#L24
      - vte3
    state: latest

- name: install gnome extensions
  ansible.builtin.command:
    cmd: |
      busctl --user call
      org.gnome.Shell
      /org/gnome/Shell
      org.gnome.Shell.Extensions InstallRemoteExtension
      s "{{ item }}"
    creates: "{{ ('~/.local/share/gnome-shell/extensions' | expanduser, item) | path_join }}"
  loop:
    # - Hide_Activities@shay.shayel.org # https://extensions.gnome.org/extension/744/hide-activities-button/
    # - sound-output-device-chooser@kgshank.net # https://extensions.gnome.org/extension/906/sound-output-device-chooser/
    - ProxySwitcher@flannaghan.com # https://extensions.gnome.org/extension/771/proxy-switcher/
    - appindicatorsupport@rgcjonas.gmail.com # https://extensions.gnome.org/extension/615/appindicator-support/
    # - hide-keyboard-layout@sitnik.ru # https://extensions.gnome.org/extension/2848/hide-keyboard-layout/
    - rocketbar@chepkun.github.com # https://extensions.gnome.org/extension/5180/rocketbar/
    - system-monitor-next@paradoxxx.zero.gmail.com # https://extensions.gnome.org/extension/3010/system-monitor-next/
    - ddterm@amezin.github.com # https://extensions.gnome.org/extension/3780/ddterm/
    # - gsconnect@andyholmes.github.io # https://extensions.gnome.org/extension/1319/gsconnect/
    # - gtktitlebar@velitasali.github.io # https://extensions.gnome.org/extension/1732/gtk-title-bar/
    # - executor@raujonas.github.io # https://extensions.gnome.org/extension/2932/executor/
    # - forge@jmmaranan.com # https://extensions.gnome.org/extension/4481/forge/
    # - arch-update@RaphaelRochet # https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
    # - dash-to-panel@jderose9.github.com  # use rocketbar instead
    # - disconnect-wifi@kgshank.net # https://extensions.gnome.org/extension/904/disconnect-wifi/
    # - PersianCalendar@oxygenws.com # https://extensions.gnome.org/extension/240/persian-calendar/
    - shamsi-calendar@gnome.scr.ir # https://extensions.gnome.org/extension/3618/shamsi-calendar/
    # - Vitals@CoreCoding.com # https://extensions.gnome.org/extension/1460/vitals/
    # - arcmenu@arcmenu.com # https://extensions.gnome.org/extension/3628/arcmenu/
    # - guillotine@fopdoodle.net # https://extensions.gnome.org/extension/3981/guillotine/
    # - no-overview@fthx # https://extensions.gnome.org/extension/4099/no-overview/

- name: clone/update Graphite-gtk-theme git repo
  ansible.builtin.git:
    repo: git@github.com:vinceliuice/Graphite-gtk-theme.git
    dest: "{{ repos_dir }}/graphite-gtk-theme"

- name: install Graphite gtk theme
  ansible.builtin.command: "{{ repos_dir }}/graphite-gtk-theme/install.sh --tweaks nord rimless normal"

- name: enable Graphite gtk theme
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    value: Graphite-Light-nord

- name: install qogir icon theme
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: qogir-icon-theme
    state: present

- name: set cursor theme to "Qogir"
  gsettings:
    schema: org.gnome.desktop.interface
    key: cursor-theme
    value: Qogir-dark

- name: set monospace font to "JetBrainsMono Nerd Font"
  gsettings:
    schema: org.gnome.desktop.interface
    key: monospace-font-name
    value: JetBrainsMono Nerd Font 10

- name: some gnome settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - schema: org.gnome.shell.app-switcher
      key: current-workspace-only
      value: "true"
    - schema: org.gnome.desktop.peripherals.touchpad
      key: tap-to-click
      value: "true"
    - schema: org.gnome.desktop.peripherals.touchpad
      key: two-finger-scrolling-enabled
      value: "true"
    - schema: org.gnome.desktop.sound
      key: event-sounds
      value: "false"
    - schema: org.gnome.desktop.input-sources
      key: sources
      value: "[('xkb', 'us'), ('xkb', 'ir')]"
    # scroll up/down instead of zoom in/out in gnome image viewer (eog)
    # https://gitlab.gnome.org/GNOME/eog/-/issues/84
    - schema: org.gnome.eog.view
      key: scroll-wheel-zoom
      value: "false"
    - schema: org.gnome.desktop.wm.preferences
      key: button-layout
      value: "appmenu:minimize,maximize,close"

- name: configure file manager
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - schema: org.gnome.nautilus.icon-view
      key: default-zoom-level
      value: "small-plus"
    - schema: org.gnome.nautilus.list-view
      key: default-zoom-level
      value: "small"
    - schema: org.gnome.nautilus.preferences
      key: default-folder-viewer
      value: "list-view"
    - schema: org.gtk.gtk4.Settings.FileChooser
      key: sort-directories-first
      value: "true"

- name: gnome power settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    # when inactive (on battery power): suspend
    - schema: org.gnome.settings-daemon.plugins.power
      key: sleep-inactive-battery-type
      value: "suspend"
    # when inactive (plugged in): nothing
    - schema: org.gnome.settings-daemon.plugins.power
      key: sleep-inactive-ac-type
      value: "nothing"

# https://wiki.archlinux.org/title/PipeWire#WebRTC_screen_sharing
# Test Page: https://mozilla.github.io/webrtc-landing/gum_test.html
- name: install required packages for webrtc screen sharing
  become: yes
  community.general.pacman:
    name:
      - pipewire
      - wireplumber
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
    state: latest

- name: install gnome-text-editor
  become: yes
  community.general.pacman:
    name: gnome-text-editor
    state: latest

- name: configure gnome-text-editor
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - schema: org.gnome.TextEditor
      key: indent-style
      value: "space"
    - schema: org.gnome.TextEditor
      key: tab-width
      value: 4
    - schema: org.gnome.TextEditor
      key: style-variant
      value: "dark"
    - schema: org.gnome.TextEditor
      key: show-line-numbers
      value: "true"

# https://wiki.archlinux.org/title/GNOME/Keyring#Setup_gcr
# The SSH functionality is disabled by default in gnome-keyring-daemon builds since version 1:46.
# It has been moved into /usr/lib/user/gcr-ssh-agent, which is part of the gcr-4 package.
- name: Setup gcr
  block:
    # install gcr-4 package
    - name: install gnome gcr (https://gitlab.gnome.org/GNOME/gcr)
      become: yes
      community.general.pacman:
        name: gcr-4
        state: latest

    # Enable the `gcr-ssh-agent.socket` systemd user unit.
    - name: enable gcr-ssh-agent.socket
      ansible.builtin.systemd:
        scope: user
        name: gcr-ssh-agent.socket
        enabled: yes

    - name: create ~/.config/environment.d directory
      ansible.builtin.file:
        path: ~/.config/environment.d
        state: directory
        recurse: true

    # https://wiki.archlinux.org/title/Environment_variables#Per_Wayland_session
    - name: configure SSH_AUTH_SOCK environment variable
      ansible.builtin.copy:
        content: SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
        dest: ~/.config/environment.d/ssh-agent.conf
