- name: update pacman cache
  become: yes
  community.general.pacman:
    update_cache: yes

- name: install useful packages
  become: yes
  community.general.pacman:
    name:
      - git
      - tig
      - man-db
      - vim
      - htop
      - iotop
      - tree
      - dos2unix
      - ncdu
      - unzip
      - lnav
      - multitail
      - xclip
      - tilda
    state: latest
