- name: update pacman cache
  become: yes
  community.general.pacman:
    update_cache: yes

- name: install git, tig
  become: yes
  community.general.pacman:
    name:
      - git
      - tig
    state: latest

- name: install vim, htop, iotop, tree, dos2unix, ncdu, unzip, lnav, multitail
  become: yes
  community.general.pacman:
    name:
      - vim
      - htop
      - iotop
      - tree
      - dos2unix
      - ncdu
      - unzip
      - lnav
      - multitail
      - xclip
    state: latest

- name: install tilda
  become: yes
  community.general.pacman:
    name:
      - tilda
    state: latest
