- name: update pacman cache
  become: yes
  community.general.pacman:
    update_cache: yes
  when: ansible_os_family == "Archlinux"

- name: update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install useful packages
  become: yes
  ansible.builtin.package:
    name:
      - git
      - tig
      - man-db
      - vim
      - htop
      - iotop
      - tree
      - dos2unix
      - ncdu
      - unzip
      - lnav
      - multitail
      - xclip
      - tilda
      - nodejs
      - npm
      - gimp
    state: latest
