- name: install packages required by pyenv (https://github.com/pyenv/pyenv/wiki#suggested-build-environment)
  ansible.builtin.package:
    name:
      - base-devel
      - openssl
      - zlib
      - xz
    state: present
  become: yes

- name: install pyenv
  ansible.builtin.git:
    repo: git@github.com:pyenv/pyenv.git
    dest: ~/.pyenv
    version: master

- name: install pyenv-virtualenv
  ansible.builtin.git:
    repo: git@github.com:pyenv/pyenv-virtualenv.git
    dest: ~/.pyenv/plugins/pyenv-virtualenv
    version: master
