- name: install pip and pipx
  become: yes
  community.general.pacman:
    name:
      - python-pip
      - python-pipx

- name: install virtualenv
  community.general.pipx:
    name: virtualenv
    state: latest

- name: install poetry
  community.general.pipx:
    name: poetry
    state: latest
