- name: remove .ssh directory of `root` user
  become: yes
  ansible.builtin.file:
    path: /root/.ssh
    state: absent

- name: remove password of `root` user
  become: yes
  ansible.builtin.user:
    name: root
    password: '!'
