- name: install ZSH shell
  become: yes
  ansible.builtin.package:
    name: zsh
    state: latest

- name: get ZSH binary path
  ansible.builtin.shell: which zsh
  register: which_zsh

- name: set ZSH as default shell
  become: yes
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ which_zsh.stdout }}"

- name: install prezto
  ansible.builtin.file:
    src: "{{ playbook_dir }}/submodules/prezto"
    dest: ~/.zprezto
    state: link

- name: install prezto
  ansible.builtin.file:
    src: "{{ playbook_dir }}/submodules/prezto/runcoms/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: link files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
    - zshrc-dotenv
    - zprofile-dotenv
    - vimrc
    - p10k.zsh

- name: install base16-shell
  ansible.builtin.file:
    src: "{{ playbook_dir }}/submodules/base16-shell"
    dest: ~/.base16-shell
    state: link