- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- name: update openssh
  ansible.builtin.apt:
    name:
      - openssh-server
      - openssh-client
    state: latest

- name: install useful packages
  ansible.builtin.apt:
    name:
      - git
      - tig
      - vim
      - htop
      - iotop
      - bmon
      - tree
      - dos2unix
      - ncdu
      - unzip
      - lnav
      - multitail
      - fail2ban
    state: latest
