- name: generate grub config
  become: yes
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg

- name: restart docker service
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: restarted
