# https://www.everythingcli.org/ssh-tunnelling-for-fun-and-profit-autossh/
# https://linux.die.net/man/1/autossh

- name: install autossh, proxychains
  become: yes
  ansible.builtin.package:
    name:
      - autossh
      - proxychains
    state: latest

- name: configure proxychains
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/proxychains.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.replace }}"
  with_items:
    - regexp: "^#?socks5 .*"
      replace: "socks5         127.0.0.1 {{ lookup('env', 'PROXY_SOCKS_PORT') }}"
    - regexp: "^#?(socks4 .*)"
      replace: "#socks4         127.0.0.1 9050"

- name: create user systemd directory
  ansible.builtin.file:
    path: ~/.config/systemd/user
    state: directory
    recurse: yes

- name: install proxy systemd services
  ansible.builtin.template:
    src: "{{ item }}.service"
    dest: ~/.config/systemd/user/{{ item }}.service
  with_items:
    - proxy-socks
    - proxy-https
  notify:
    - restart proxy services

- name: force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: enable proxy services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  with_items:
    - proxy-socks
    - proxy-https

- meta: flush_handlers
